spring.application.name=spendings

spring.datasource.url=jdbc:postgresql://localhost:5432/spendings
spring.datasource.username=postgres
spring.datasource.password=admin


spring.jpa.show-sql=true

jwt.secret=QosV7INNxb9TxflEw5lYFzz9hj0iCvjx967d5yVlAxo