CREATE TABLE expenses
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount         DOUBLE PRECISION                        NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    description    VARCHAR(255),
    payment_method VARCHAR(255),
    category_id    BIGINT,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_expenses PRIMARY KEY (id)
);

ALTER TABLE categories
    ADD created_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE categories
    ADD updated_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE expenses
    ADD CONSTRAINT FK_EXPENSES_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);